applications:

  hello:
    enabled: true
    path: values/local-example/applications/dev/hello

  cnpg-database:
    enabled: true
    path: values/local-example/platform/database/

  raw:
    enabled: false
    path: values/local-example/platform/raw

helmCharts:
  keycloak:
    enabled: true

  keycloak-operator:
    enabled: true

  ingress-nginx:
    enabled: true
    ignoreDifferences:
      - group: ""
        kind: Service
        jqPathExpressions:
          - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: true

  sealed-secrets:
    enabled: true

  ingresses:
    enabled: true

  vault:
    enabled: false

  # Microservice helm charts for the dev environment

  todolist-frontend-dev:
    enabled: false
    values: defaults/applications/dev/todolist/frontend/values.yaml

  todolist-backend-dev:
    enabled: false
    values: defaults/applications/dev/todolist/backend/values.yaml

  show-env-dev:
    enabled: true
    values: defaults/applications/dev/show-env/values.yaml

# Microservice helm charts for the tst environment

  todolist-frontend-tst:
    enabled: false
    values: defaults/applications/tst/todolist/frontend/values.yaml


# Microservice helm charts for the prd environment

  todolist-frontend-prd:
    enabled: false
    values: defaults/applications/prd/todolist/frontend/values.yaml
