# some of the values will be filled by install.sh script
global:
  platformName: x
  domain: x
  automated: true
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: x
      targetRevision: x
    values:
      repoURL: x
      targetRevision: x

kustomize: # kustomize applications and also raw folders

  cnpg-database:
    enabled: false
    namespace: cloudnative-pg

  raw:
    enabled: false

  dashboards:
    enabled: false
    namespace: monitoring


helm:

  argocd-image-updater:
    enabled: false
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.11.1
    chart: argocd-image-updater
    namespace: argocd

  keycloak:
    enabled: false
    syncWave: 0
    path: templates/keycloak

  ingress-nginx:
    enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx

  kube-prometheus-stack:
    enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 65.8.1
    chart: kube-prometheus-stack

  loki:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.79.4
    chart: loki-distributed

  promtail:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.16.6
    chart: promtail

  cert-manager:
    enabled: false
    namespace: cert-manager

  cloudnative-pg:
    enabled: false
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg

  pgadmin:
    enabled: false

  ingresses:
    enabled: false

  # Applications

  show-env:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  backend-https:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  identityserver:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  openiddictserver:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications
