global:
  platformName: x
  domain: x
  automated: true
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: x
      targetRevision: x
    values:
      repoURL: x
      targetRevision: x

applications:

  cnpg-database:
    enabled: false
    namespace: cloudnative-pg

  raw:
    enabled: true


helmCharts:

  keycloak:
    enabled: false
    path: templates/keycloak

  keycloak-operator:
    enabled: false

  ingress-nginx:
    enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.1
    chart: ingress-nginx

  kube-prometheus-stack:
    enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 56.7.0
    chart: kube-prometheus-stack

  loki:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.78.2
    chart: loki-distributed

  promtail:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.15.5
    chart: promtail

  cert-manager:
    enabled: false
    namespace: cert-manager

  cloudnative-pg:
    enabled: false
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg

  pgadmin:
    enabled: false

  ingresses:
    enabled: false

  identityserver:
    enabled: false
    path: templates/generic-deployment

  openiddictserver:
    enabled: false
    path: templates/generic-deployment
