applications:

  cnpg-database:
    enabled: true
    path: values/oidcproxy-dev-env/platform/database/

  raw:
    enabled: false
    path: values/oidcproxy-dev-env/platform/raw

helmCharts:
  keycloak:
    enabled: true

  keycloak-operator:
    enabled: true

  ingress-nginx:
    enabled: true
    ignoreDifferences:
      - group: ""
        kind: Service
        jqPathExpressions:
          - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: false

  cert-manager:
    enabled: true

  ingresses:
    enabled: true

  identityserver:
    enabled: true
    values: oidcproxy-dev-env/platform/identityserver/values.yaml

  openiddictserver:
    enabled: true
    values: oidcproxy-dev-env/platform/openiddictserver/values.yaml
