services:
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
  - name: keycloak
    serviceName: keycloak-keycloakx-http
  - name: grafana
    namespace: monitoring
    serviceName: kube-prometheus-stack-grafana
  - name: prometheus
    namespace: monitoring
    subdomain: prometheus
    serviceName: kube-prometheus-stack-prometheus
    port: 9090
