apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-deployment.fullname" . }}
  labels:
    {{- include "generic-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- /* Determine service port based on useHttps */}}
  {{- $servicePort := .Values.service.ports.http }}
  {{- if .Values.useHttps }}
    {{- $servicePort = .Values.service.ports.https }}
  {{- end }}
  ports:
    - name: {{ if .Values.useHttps }}https{{ else }}http{{ end }}
      port: {{ $servicePort }}
      targetPort: {{ if .Values.useHttps }}https{{ else }}http{{ end }}
  selector:
    {{- include "generic-deployment.selectorLabels" . | nindent 4 }}
