fullnameOverride: identityserver

image:
  repository: albertstarreveld/identityserver
  tag: 2.0

replicaCount: 1

service:
  port: 8081

volumes: |
  - name: identityserver-tls-volume
    secret:
      secretName: identityserver-tls-secret
volumeMounts: |
  - name: identityserver-tls-volume
    mountPath: "/etc/x509/https"
    readOnly: true
