grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-gateway
        isDefault: false

  adminPassword: ""
  admin:
    existingSecret: grafana-admin
    passwordKey: admin-password
    userKey: admin-user

prometheus:
  prometheusSpec:
    # Select all ServiceMonitors
    serviceMonitorSelector: {}
    # Select all PodMonitors
    podMonitorSelector: {}
    # Select ServiceMonitors from all namespaces
    serviceMonitorNamespaceSelector: {}
    # Select PodMonitors from all namespaces
    podMonitorNamespaceSelector: {}
    # Allow selection of ServiceMonitors from all namespaces
    serviceMonitorSelectorNilUsesHelmValues: false
    # Allow selection of PodMonitors from all namespaces
    podMonitorSelectorNilUsesHelmValues: false
