{{- range $name, $app := .Values.helm -}}
{{- if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default 0 .syncWave }}"
    {{- if .annotations }}
      {{- toYaml .annotations | nindent 4 }}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    team: platform
spec:
  project: {{ $.Values.global.platformName }}
  sources:
  - repoURL:  {{ default $.Values.global.spec.source.repoURL .repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    {{- if hasKey . "chart"}}
    chart: {{ .chart }}
    {{- else if hasKey . "path"}}
    path: {{ .path }}
    {{- else }}
    path: templates/{{ $name }}
    {{- end }}
    helm:
      valueFiles:
        {{- if hasKey . "values"}}
        - "$valuesRepo/{{ .values }}"
        {{- else if hasKey . "valuesFolder"}} # it means that the values are not in default folder (which is platform) [for example to use for applications folder]
        - "$valuesRepo/values/defaults/{{ .valuesFolder }}/{{ $name }}/values.yaml"
        - "$valuesRepo/values/{{ $.Values.global.platformName }}/{{ .valuesFolder }}/{{ $name }}/values.yaml"
        {{- else }} # default values folder is platform folder
        - "$valuesRepo/values/defaults/platform/{{ $name }}/values.yaml"
        - "$valuesRepo/values/{{ $.Values.global.platformName }}/platform/{{ $name }}/values.yaml"
        {{- end }}
      parameters:
        - name: domain
          value: {{ $.Values.global.domain }}
  - repoURL: {{ $.Values.global.spec.values.repoURL }}
    targetRevision: {{ default $.Values.global.spec.values.targetRevision .valuesTargetRevision }}
    ref: valuesRepo
  destination:
    namespace: {{ default $name .namespace }}
    server: {{ default $.Values.global.spec.destination.server .destinationServer }}
  syncPolicy:
    {{- if default $.Values.global.automated .automated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
