image:
  repository: albertstarreveld/identityserver
  tag: "3.0"

replicaCount: 1

useHttps: true

containerPorts:
  https: 8081

service:
  type: ClusterIP
  ports:
    https: 8081

env:
  PFX_BASE64: MIIQnwIBAzCCEFUGCSqGSIb3DQEHAaCCEEYEghBCMIIQPjCCCqoGCSqGSIb3DQEHBqCCCpswggqXAgEAMIIKkAYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBD84lJ8OZ3qVaqLBTM/dNZaAgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQkog0brXz6W9wNJmxSqlLF4CCCiASRtdGHJeUI40h363gVHLdEqM9rcu9l2HeTDJtpzcWa4TDHs62qpQnYQIy0GKFpXYQK1T/UOJty+BpoGzUuugFffjJSTfFqAZd34ddaAuWgfTQ4SByHNrbXQyHRZYYuELpBtHOsYBavW0Rof+xpyi+XRMYXo9xxLqeBTyREybHkbmaBfAbaFsbmUILzGe1PCM1fVSLhrk6/V2lQCWQax1v9+i6CxjegAesQsPMiEvWmtQbFWU1G3rQBj1xNYHqKY2kYaq9Q8UjZGvIMf8rtEmmbTCT694fbMLJ2y4n2fYFBlLiVj1hqBN2XeShAvpjAVWv3P/V4uRVpfi14Xx1/koDY4FUipVNXxBceLE91clqVVT2XdAPyN1jcumqe1vKWbyqM8n/BjsvDA8btRVR7/jQ1E42WSrtfb6Wyy/12kWl89xforFfGfXDPGtprDY+dwfjGssbYvDolltz9+hWr8TvN8VWP2sfg0hC98SRQBYgGu+pVY1qjg022Y+8YRaRpr+T90+udvSNYuf8i2VEiKI/sxDQlRtXiB/L/q5/uk1qmVSA7bsZPgNJ67Se8puLVR2B2iaceHBgLd85ObqYRg2Spvh1m7K1PIP9tjDTaqD0Snt37AUgg8ITDmebWQ2D/nplCJFvm06S9V+iku7gHjFmN1201mUJJc2M33WCM5H40SB5x05EV1coUVHk4YIliNYTdMNYPzZZcTQM0cGzeAEuBppEK574eT+7+3LEIt/AsfwFwYRXQnc2SVSmSrBcK8s6B74vWU+42jdFbYP+cLCdhj5iXst00O6/MFFOcK7HjUZ9s80yUn4xpwrhMvoK/cWIZDMCgqLkCa/KCTl0N+NpW7Og7rFElatIvhIsLnKQb+I+3AT2ZklnETckKcuVzJd1TIEO26gbW4Gw6l5VuIilsMCCWHfn+/h+8dRpUU1+TqjjzXNzPBe3MRZN1PBeize3LaWe+0OX+h4vcR2y3NWZ3QrhqfMdCeboxugjPaG0USflvfKWmMIAnHtLr+GO42wUnSxkuCDAeOqcDr0HT0ueO79iJTM/S/CDlHq/KD/9KOz7lvoRt/KEToxk+5MxCZslHb9DBIB1WeO1eJRrHtWq6PCUM866+zWLFY4UAhT9jXZeRLMDo4H01LQeNmjReom2kWHojAaO8HKdBYAUt1szy6D5TzfOV+hmXSozNgta9XMnfkuIlsR5Ii9wmrwEXDIs0F50QvTiIYMJfEZ5QiZLUHpS+R4MJ6FeBzKy4OT1hvNFNNwbe3Hdu1uM3/yHufQKvTRAChhCYaaeyz29gOrHG8KOYmRkbmcwYw5CpKF8TSeWtzYsUNsg3u+zYjAYaIW53B82KnNZ/o+ulpjdlnBmQepHE9GThELr+EiKdCeZzcx1DGjbt+RgWqyEza2CAl2P0KYrcqY5gM7qwzzSBtDVpgpd90tfdDqUeW58mmEphO1O2PmooncsPFbzGvpLT5b0WAADyZphwUeTGmC/o8Ys4hf8fP7cJFm1xO+l+EAHe5gaBLjUHebzLhmq5mjceoc9CrY/RIgsMXgJ52hW/vCqwkgSWNtkP/huIpDlMY2pxiPZV/7Tmzt0oWkrqPL4FzgcgYnwubSb1BtEpIZlVCnHtH8GSb07+66TZL7xQKxUqlk5S+30HllMQ929dqWCALhLTKFzPALveMSqT88Ul0rRAdW2t3+gq8HF1W6cRQpsS4eax//RWH13fxZ7TLG/PrxCyV8FLQWdo6ww6lL6WMEOVkWWbWp6bqGM8KkZ5lF4UNxI27AaiZ8za0KMOQ4s5WwTWsPmw2QxxWTFDlMg7osgtH3af9V8ACtO4+VYUH8GXT7zT47mm3oik/t/wX5jRzAe54Q+FXM2QNTylJDglREXPELr80Sh9IrddWdT7bsiWy4gOgUF0X2Ugqyxn27o0UDTFk8ud6ZhwsxkYaCpeSBs+xtnaB6vS5da6shAxqiNB4De0bE13C9oqe7W6xcUjxMQSREVI9+Zt1CMhAw01/mQmMLWQAQkFNUuJQ+fBE6oR7u1JYEbvuTQPeB9jgKnx9BVOQsl0s+D2BwFjGeM7swJJ7wVfQFeKqpSLWn+xVzRTR5u1fWbw/QTxkxtZ3e9H/clxSzej+RBE02Qg5v73k+WksojkDM+N2t5IhWgJOx/mQlBDRbX7frfkmtA7YKm4XvT1vp0O8YRWwmYOjCdOP2bDEBfB6RQ/himdRQc16jjCNH/XWsyYMVUbO0KGvMeHXatmnKNir8UtVDumzZPIj7Xwh0eNMOVAievPAVl/PZcKxeBOQsD30rJfcfl0fHIoE+qdRabAOIRanQELkLEnZwE6PkDpAGu/W4Y6dNecRJGSWsJId2hhNrNaDMWMtAFOaFy5fKmg6CUU3wtjTeizNpMt08wdC1C3DsN1U+Mp2mVITv4OxJ6oBSH1Tkmzr7+KGWk0FbRPx816IqrgvYU5bBbxTzjERiylpkFZmarqHNcXxe5LCpPWA8nw2kaXei2IriXBswVEEvtPlh2snTfegvihTMFW34Q8byttKXylS5FN7ri1OFdYU8k8/60yt8nw+7b1VQlls8Zfej/d8burGVNlwXoFsFvy59HsKVxBUzYfEZ26KzVo2buiQqqHrwt6oACim0i3RD/pJpQIhj03vyQMpj7tmzho500sdzdzfAKJWCVqUmapX3a9j4mjrDGpHvv9+jmBoob1lVvWxb21EQyO2Lp1ruWeLTjnL8XXFjZQsMpmZ8CLUPxIhcTBovEBIvVjZXnTALssx6GPj+JsVAFRkXF/8jQNxUjJd21SdlWd/QC7RS0+VxtnABHFZiWK8tPag1/ESWXgPXrPsAe4VkYvcXUFwl7cb3Vmb8EUZMuQwHdC7uZs18ANQ/fHqWDEaEn0sEY5R2n/pxpu/qRch2/4Gem1QAaTOkxG9owL2MPwgeuUk7OIOSZcjVamHLM3XeoMHffUjFs7zATaFI1Woh1G7uUSbkJLtqayaB2izO+oKn/+IVNtd0K6lYZwk+c+Ysivp0K+depLiVWL7P9fD5IE9UXY5hhbdNu6EyKLnheYbZn6E3wI8wOJFnSKjJq945oDZRmvCToOqmiEExDcbkc4oH+AxpdVx94bl1+LYVPZ0YE6FK7g28aKTD3UCPAw4v/gFpNotRcSigvlr/9TreHyT1kxrMngF67URH/2zd+Z7NRX5YFAiAE/SgNl/gSBO/LuZXzfTXqzIXOUjtrRHlpTnvTdL0jh8A3XNLadqRilbjcTCJwuOvvxXF+XOJ1kyJCG1TqEkWxIJHUfChWqnY4RfDBvTYfx6dOG5KGNT5tVzcke3yDhhCeFPEtTajxQVGupbVQBBfYNIbAI/sPgMNO20X2Oz3X9942xS/Vh5k0FJNeBkoWnyWz945ua6XB1goSqhhgzvqd3cfPghgPMfRwqDV1LMRlg7UfKYR1ya4ik5fhacOm7DdIqA5tCibtvBswggWMBgkqhkiG9w0BBwGgggV9BIIFeTCCBXUwggVxBgsqhkiG9w0BDAoBAqCCBTkwggU1MF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBDrqRlLCKkAA/4+BJhpOkcGAgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQfKmDzvrP1kenMgmnNyQ8HgSCBNADm3wuWlJjDLXQl5GDsNbxvKjRwWLJxdmjmYXe6aUxogur8+uoDEpZWVYQ59lnXAdjqaLGzRDGwTIRBZrGZWQdWz6QIWYSfimo7PQBKVaGeo8bKegRrY4310Z83OCE+qQjn/sCNqJFkHcYuCYN5baaOy6YN4lY2X4zF+t9BrRFKagf+jn4xMiS67pL6s35QQ4SuS0ZqE2dL+UDgpPcDI2PuNpttPBlYoZTlvJYOlOGmafv5/JLrVQ9DhqVwjXqtYz9Ro3rR47c8+7SMo1dPQBz097S2IM4VOeltcHqkgzvA+/ulckzrRDrS6b2W4sKXFzrcUkFWiPF143639MKrwiWBUaY1j42I8l2e6uGM6ZcQq3k7YuT2ZQmZkuxD7bC3Gh+bz2IVWIl75tQqIhcDJBMJqA7FXdwUlkl53iZe4adD6qADr9BFultJidfgJsXXhzMc850efr/2kjHONpi6cXVUEu8M605bwU46SjW8OSSt3WHIT+mWlRO3OZOvz8/sMz54/FMlqMifiOyPLXIrUenSuzfj0OsjGm2AZWK9rXmPUvvPeFETty6VXyblUhD0IsbOMoVrTDrSILvdCp8+P6UReNrErfMFTe0F8R/ZXj3zxTs50vjBaYnHEEg86OAG63qdvn4veQERtRwgucfHd3MYegbiXFV0g/rwQa595adQ6gokPlZ6aLk+nzs8cvaRQwwdTUq0kBB5p93WsxSz/mBd3MIrgWg8hsToYMpkvzryKTiMTd0+NpQSkF2Jwgi3WLTns6Ee15kQ6cfxPGgtNa6tFRCQGvxaR0xQ2JRsA8+BPDh+G2V+/Ys1twCBtaOCIYuhmt1iECUb6ZXkQpX+erpWDKvontMQLgmLcLvPcGKbb52uCw31wnyUDfDaEwadwwn7QL7MwNk+sjMKSa+39LRJP+jTRq0TlP5plPdX2ACtSGy7xwhMvOOJlCaVCzcXhruZVKVKtxozQbKDxzMIyReYb2Cwed2uMzCFkl3Z1+BFEPnhaiButOxuy7mgpnfe//thcVUJwOGTwoKfZl7EqzXqkGfbNBLNZ8O0BdrR12AOSUpxYQLmpJ8ccLvOkhjYCSxzir0PZc2svZdOE/L7eZjvEDOlcBexBUcaoORaVJQfu7Vq2rLLO67SX+1e68LqOfy20hPZpV4+RUfdVKLfu3idaBLt/TdaE6CM2JAW/KvdxoJB76smGioM2LnFP2YqulKKCqZgwwSIh7zQZ+DB6rh9u0RxLa/Fg/qQ6hQHlpfk9JR2dvQY6IHgwempXUpvZmbZKd850si4piVuCrrx2oQt/0vuLHlJ34biWtHc/F18dwiOwzudP2gxrPwOwNRuIWyQySmuOPRg4Au/AbL/LwiVpTpEaj7XaCIX1YSMYcD/xtJ7lWG+taVxt/hdY1pQSGaOM5svQM4DQW+1EFHvrgNMd/emNaAoODVr7lD6b1+94xEVkXkc7xkLRfHlnFrCVzt97RNx0IvVDEm9HRmagJHj/b3r8t8U0WjrYdyEI5HrGQDJaIMjxXvUvCoHrun++SGc0JxXPTMKzBm3zaItV93UaotbYWHwvG1wasMkcI8PhgZXPgTcmbvdELsN0Cbg+tM7LKppt0V1yc78ln4b19oBWjXbnAvmdLnrDFRVEYQJDElMCMGCSqGSIb3DQEJFTEWBBQ5AveQNppLAFZU2DqOHaLWfXRmrzBBMDEwDQYJYIZIAWUDBAIBBQAEIJqSVEXa01xZMCn0JOnrmo5Xm43fhp+6JEyecKkXFJmfBAjodDL3IPlG7gICCAA=
  Kestrel__Certificates__Default__Path: https_certificate.pfx
  Kestrel__Certificates__Default__Password: "123456"
  ASPNETCORE_URLS: "https://0.0.0.0:8081"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "selfsigned-clusterissuer"
  tls:
   - secretName: "tls-certificate"
     hosts:
       - '{{ include "generic-deployment.fullname" . }}.{{ $.Values.domain }}'


livenessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30
